<template>
  <TheTable v-if="org?.length" :instance="instance" />
  <div v-else>Nothing to Show</div>
</template>

<script setup lang="ts">
import {
  createColumnHelper,
  getCoreRowModel,
  getSortedRowModel,
  useVueTable,
  type SortingState,
} from "@tanstack/vue-table";
import { computed, ref } from "vue";
import TheTable from "./TheTable.vue";
// import { date } from "quasar";
import useGetLoans from "@/utils/composables/API/admin/useGetLoans";

// type DataType = {
//   applicationId: number;
//   loanName: string;
//   generatedBy: string;
//   loanAmount: number;
//   appSource: string;
//   draftApplicationID: string;
//   applicationStatus: string;
//   submissionDate: string;
//   lvr: number;
//   lastChangedDate: string;
//   canResubmit: boolean;
//   currentDecisionStatus: string; // named as rules in table
// };

interface Application {
  applicationId: number;
  applicationStatus: string;
  applicationType?: string;
  borrowerId?: number;
  clientId?: number;
  caseId?: number;
  sourceId?: number;
  eligibilityApplicationId?: number;
  userId?: number;
  isJointApplication?: number;
  idType?: string;
  createdDate: Date;
  creditCardAppId?: number;
  personalLoanAppId?: number;
  vehicleLoanAppId?: number;
  firstCitizenshipDetailsId?: number;
  secondCitizenshipDetailsId?: number;
  firstEmploymentDetailsId: number;
  secondEmploymentDetailsId?: number;
  firstIncomeDetailsId?: number;
  secondIncomeDetailsId?: number;
  firstPersonalDetailsId: number;
  secondPersonalDetailsId?: number;
  firstPersonIdentityDetailsId?: number;
  secondPersonIdentityDetailsId?: number;
}

interface Applicant {
  personalDetailsId: number;
  applicationId: number;
  userId?: number;
  isFirstPerson: number;
  title: string;
  firstName: string;
  middleName: string;
  lastName: string;
  dob?: Date;
  gender: string;
  address: string;
  email: string;
  mobileNumber: string;
  maritalStatus: string;
  numberOfDependents: number;
  isSecondPersonPartner?: 0 | 1;
}
interface DraftApplication {
  draftId: number;
  email: string;
  phoneNumber: string;
  draftStepUrl: string;
  applicationStatus: string;
  createdAt: string;
  updatedAt: string;
  applicationId: number;
}
interface DataType {
  application: Application;
  applicant: Applicant;
  draftApplication: DraftApplication;
}

const { data: org } = useGetLoans();

const columnHelper = createColumnHelper<DataType>();
const host = window.location.origin;
const columns = [
  columnHelper.accessor("application.applicationId", {
    header: () => "APPLICATION ID",
  }),
  columnHelper.accessor("applicant.firstName", {
    header: () => "LOAN NAME",
  }),
  columnHelper.accessor("application.applicationType", {
    header: () => "LOAN TYPE",
  }),
  columnHelper.accessor("draftApplication.email", {
    header: () => "EMAIL",
  }),
  columnHelper.accessor("draftApplication.phoneNumber", {
    header: () => "PHONE",
  }),
  columnHelper.accessor("draftApplication.draftStepUrl", {
    header: () => "DRAFT STEP URL",
    cell: ({ getValue }) => {
      const url = host + getValue();
      return url;
    },
  }),
  // columnHelper.accessor("generatedBy", {
  //   header: () => "GENERATED BY",
  // }),
  // columnHelper.accessor("submissionDate", {
  //   header: () => "SUBMITTED",
  //   cell: ({ getValue }) => date.formatDate(getValue(), "DD MMM YYYY"),
  // }),
  // columnHelper.accessor("application.applicationStatus", {
  //   header: () => "STATUS",
  // }),
  // columnHelper.accessor("lastChangedDate", {
  //   header: () => "LAST MODIFIED",
  //   cell: ({ getValue }) => date.formatDate(getValue(), "DD MMM YYYY"),
  // }),
  // columnHelper.accessor("loanAmount", {
  //   header: () => "LOAN AMOUNT",
  //   cell: ({ getValue }) => "$" + getValue(),
  // }),
  // columnHelper.accessor("lvr", {
  //   header: () => "LVR RATIO",
  // }),
  // columnHelper.accessor("currentDecisionStatus", {
  //   header: () => "RULES",
  // }),
];

// const data = reactive<DataType[]>([
//   {
//     appSource: "OP",
//     draftApplicationID: "c54b2578-e62b-4f7a-832b-f8c72701d5f0",
//     applicationId: 15766,
//     loanName: "Jax Doe",
//     applicationStatus: "New",
//     submissionDate: null,
//     loanAmount: 0,
//     lvr: 0,
//     lastChangedDate: "2023-02-01T13:12:32.423",
//     canResubmit: false,
//     generatedBy: "Sandeep Prasad",
//     currentDecisionStatus: "",
//   },
//   {
//     appSource: "OP",
//     draftApplicationID: "b651eebf-8024-4544-9aa3-ec94def72a9d",
//     applicationId: 15767,
//     loanName: "James Doe",
//     applicationStatus: "New",
//     submissionDate: null,
//     loanAmount: 800000,
//     lvr: 64.8,
//     lastChangedDate: "2023-01-31T18:52:55.013",
//     canResubmit: false,
//     generatedBy: "Sandeep Prasad",
//     currentDecisionStatus: "",
//   },
//   {
//     appSource: "OP",
//     draftApplicationID: "758c3d47-81e8-4b83-bd51-3e0a19d6e270",
//     applicationId: 15768,
//     loanName: "Test Applcation",
//     applicationStatus: "New",
//     submissionDate: null,
//     loanAmount: 0,
//     lvr: 0,
//     lastChangedDate: "2023-01-04T12:38:14.33",
//     canResubmit: false,
//     generatedBy: "Sandeep Prasad",
//     currentDecisionStatus: "",
//   },
//   {
//     appSource: "OP",
//     draftApplicationID: "e241eb2b-19b1-44cb-981f-abf01a1ebe1f",
//     applicationId: 15769,
//     loanName: "Janet Doe",
//     applicationStatus: "New",
//     submissionDate: null,
//     loanAmount: 0,
//     lvr: 0,
//     lastChangedDate: "2023-01-04T12:37:53.563",
//     canResubmit: false,
//     generatedBy: "Sandeep Prasad",
//     currentDecisionStatus: "",
//   },
//   {
//     appSource: "LW",
//     draftApplicationID: null,
//     applicationId: 17152,
//     loanName: "BECCAFBE, EEDCC DBCBBA / DFDABFCC, ACFCB AEFA / Kabu",
//     applicationStatus: "Application Received",
//     submissionDate: "2020-08-03T00:00:00",
//     loanAmount: 830000,
//     lvr: 39.15,
//     lastChangedDate: "2022-09-28T23:03:00.887",
//     canResubmit: false,
//     generatedBy: "",
//     currentDecisionStatus: "",
//   },
//   {
//     appSource: "LW",
//     draftApplicationID: null,
//     applicationId: 15761,
//     loanName: "DABDBC, ADB / BEABCC, DEBDEF",
//     applicationStatus: "Application Received",
//     submissionDate: "2022-08-10T00:00:00",
//     loanAmount: 800000,
//     lvr: 88.89,
//     lastChangedDate: "2022-08-23T09:30:30.263",
//     canResubmit: false,
//     generatedBy: "",
//     currentDecisionStatus: "",
//   },
//   {
//     appSource: "LW",
//     draftApplicationID: null,
//     applicationId: 15658,
//     loanName:
//       "FEAAADC, EADACBCEBBCCC / EFECEBC, AAEDAABFDAFB / CAAACDB, EBCDBDAEDEC",
//     applicationStatus: "Application Received",
//     submissionDate: "2022-08-20T00:00:00",
//     loanAmount: 750000,
//     lvr: 50,
//     lastChangedDate: "2022-08-20T09:45:00.77",
//     canResubmit: false,
//     generatedBy: "",
//     currentDecisionStatus: "Referred",
//   },
//   {
//     appSource: "LW",
//     draftApplicationID: null,
//     applicationId: 15653,
//     loanName: "BBBBDBD, FCAEEEAFC / EDF, BCCEEBCCFCD",
//     applicationStatus: "Application Received",
//     submissionDate: "2022-08-20T00:00:00",
//     loanAmount: 750000,
//     lvr: 50,
//     lastChangedDate: "2022-08-20T08:39:00.563",
//     canResubmit: false,
//     generatedBy: "",
//     currentDecisionStatus: "Pending Approval",
//   },
//   {
//     appSource: "LW",
//     draftApplicationID: "df889404-64be-42ea-9003-c0dcf92ea6f9",
//     applicationId: 17864,
//     loanName: "Rayga, Jason",
//     applicationStatus: "",
//     submissionDate: "2022-11-08T00:00:00",
//     loanAmount: 800000,
//     lvr: 40,
//     lastChangedDate: null,
//     canResubmit: false,
//     generatedBy: "Sandeep Prasad",
//     currentDecisionStatus: "",
//   },
//   {
//     appSource: "LW",
//     draftApplicationID: "ed4e5345-55a6-4108-8d81-cc5fd39ae8ad",
//     applicationId: 17865,
//     loanName: "Doe,John / Doe,Jane / Doe Corp",
//     applicationStatus: "",
//     submissionDate: "2022-11-10T00:00:00",
//     loanAmount: 1325122,
//     lvr: 66.26,
//     lastChangedDate: null,
//     canResubmit: false,
//     generatedBy: "Sandeep Prasad",
//     currentDecisionStatus: "",
//   },
//   {
//     appSource: "LW",
//     draftApplicationID: "ddaf031b-885e-4bb9-bd95-05de23c61427",
//     applicationId: 17866,
//     loanName: "Applicant One,Test / Applicant Two,Test / Three,Test Applicant",
//     applicationStatus: "",
//     submissionDate: "2022-12-09T00:00:00",
//     loanAmount: 180000,
//     lvr: 90,
//     lastChangedDate: null,
//     canResubmit: false,
//     generatedBy: "Sandeep Prasad",
//     currentDecisionStatus: "",
//   },
//   {
//     appSource: "LW",
//     draftApplicationID: "d92492a8-b214-40e2-8854-42b63485c033",
//     applicationId: 17867,
//     loanName: "Doe,Jane / Doe,Kale",
//     applicationStatus: "",
//     submissionDate: "2022-12-12T00:00:00",
//     loanAmount: 1000000,
//     lvr: 20,
//     lastChangedDate: null,
//     canResubmit: false,
//     generatedBy: "Sandeep Prasad",
//     currentDecisionStatus: "",
//   },
//   {
//     appSource: "LW",
//     draftApplicationID: "2e63369f-7354-4b52-8363-8d9e0b15c0f9",
//     applicationId: 17868,
//     loanName: "Rayga,Jason",
//     applicationStatus: "",
//     submissionDate: "2023-01-03T00:00:00",
//     loanAmount: 800000,
//     lvr: 80,
//     lastChangedDate: null,
//     canResubmit: false,
//     generatedBy: "Sandeep Prasad",
//     currentDecisionStatus: "",
//   },
// ]);

const sorting = ref<SortingState>([]);
const TableData = computed(() => org.value || []);
const instance = useVueTable({
  get data() {
    return TableData.value;
  },
  columns,
  state: {
    get sorting() {
      return sorting.value;
    },
  },
  onSortingChange: (updaterOrValue) => {
    sorting.value =
      typeof updaterOrValue === "function"
        ? updaterOrValue(sorting.value)
        : updaterOrValue;
  },
  getCoreRowModel: getCoreRowModel(),
  getSortedRowModel: getSortedRowModel(),
  debugTable: true,
});
</script>

<style scoped></style>
