trigger:
  - develop/shall/demo
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.4"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run lint
    displayName: "npm install and linting"
  # demo
  - script: |
      npm run build
    displayName: "Build"
  - task: CopyFiles@2
    inputs:
      sourceFolder: "$(Build.SourcesDirectory)"
      contents: "dist/**/*"
      targetFolder: $(Build.ArtifactStagingDirectory)/npm
    displayName: "Copy npm package"

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "$(Build.ArtifactStagingDirectory)/npm"
      artifactName: direct-portal-non-mortgage
    displayName: "Publish npm artifact"
